### ISSUE TITLE
Adding Coefficient of Variation to Jamovi Descriptive

### ISSUE THREAD

**Issue by JauntyJJS** [jamovi/jmv#221]
Hi,

Not sure if this is the right place to make a request
I would to ask if it is possible for the Coefficient of Variation could be added in the Jamovi's Descriptives section.

![image](https://user-images.githubusercontent.com/9066508/55311742-4e7aa980-5496-11e9-8282-f24944b02bdc.png)

If so, please advice on how this can be done. 

E.g what R or js script needs to be changed, how to display Inf if the mean is zero and NA if both the sd and mean are zero.

Thank you.

**Comment by jonathon-love** [comment]
hi,

this is the first i've heard of *coefficient of variation*, and we're a bit reluctant to add options that aren't commonly used, just because it adds clutter to the UI.

you *can* calculate it with the Rj Editor, not sure if that's helpful:

<img width="881" alt="Screen Shot 2019-04-01 at 19 51 11" src="https://user-images.githubusercontent.com/3240247/55315275-bbeb0200-54b7-11e9-90a6-126ea606487a.png">

**Comment by JauntyJJS** [comment]
Hi,

Noted on your decision
I actually wanted to find the Coefficient of Variation for a group of variables (say len1, len 2, len 3) split by another variable like (Sample Group: Control/GroupA/GroupB ).

**Comment by jonathon-love** [comment]
oh, actually, an easy way to do this is with the computed variable system. notice the `group_by` argument. you'll need to use jamovi 0.9.6.4 or newer for the `group_by` argument.

<img width="912" alt="Screen Shot 2019-04-02 at 12 42 33" src="https://user-images.githubusercontent.com/3240247/55370067-dae3a580-5544-11e9-9c0a-4111bd3f36f3.png">
